language: java
jdk:
  - openjdk14

sudo: false

notifications:
  email:
    recipients:
      -mazusik1@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

before_install:
  - chmod +x mvnw